# Project metadata
# (No longer using Poetry or pyproject.toml for dependency management)
# See requirements.txt for dependencies
#
# This file is now informational only. To install dependencies, run:
#   pip install -r requirements.txt
#
# You may safely delete this file if you do not need it for documentation.
